### ISSUE TITLE
[Bug] Build fails on Node 20: seen.values(...).filter is not a function in collectDuplicatedRouteNodes

### ISSUE THREAD

**Issue by cwandev** [vuejs/router#2633]
### Reproduction

https://github.com/vue-zone/vue3-vant-mobile

### Steps to reproduce the bug

1. Use `vue-router@5.0.3` with file-based routing (`vue-router/auto-routes`)
2. Build with **Node.js 20** (any 20.x version, e.g. 20.12.0 or 20.19.0)
3. Run `pnpm run build` (or any production build command)

### Expected behavior

Build completes successfully, as it does with `vue-router@5.0.2` or with Node.js 22+.

### Actual behavior

Build fails with:

```
[vite-plugin-pwa:build] [plugin vite-plugin-pwa:build] There was an error during the build:
  Could not load vue-router/auto-routes (imported by src/router/index.ts):
  seen.values(...).filter is not a function
```

### Additional information

The issue is in `collectDuplicatedRouteNodes` (`packages/router/src/unplugin/core/tree.ts`), introduced by commit 34aceb98:

```ts
const dups = Array.from(
  seen
    .values()
    .filter(nodes => Object.keys(nodes).length > 1)
    // ...
)
```

`Map.prototype.values()` returns a `MapIterator`. The `Iterator.prototype.filter()` method is part of the [Iterator Helpers proposal](https://github.com/tc39/proposal-iterator-helpers), which shipped in **V8 12.4** (Node.js 22.0.0, April 2024). On Node.js 20 (V8 11.x), iterators do not have `.filter()`, so this call throws.

Notably, the codebase is already aware of this constraint — `getChildrenDeep()` in the same file has the comment:

> Use with Array.from() for now, native .map() support in Node 22+.

Node.js 20 (Iron) is currently in **Maintenance LTS** until **April 30, 2026**. Many CI/CD platforms (Netlify, Vercel, etc.) still default to Node 20. Maintaining compatibility with Node 20 is important for the current lifecycle.
