### ISSUE TITLE
Error launching build with version v4.4.1 and v4.4.2

### ISSUE THREAD

**Issue by matteoscaramuzza** [vuejs/router#2320]
### Reproduction

Launch the build

### Steps to reproduce the bug

Launch npm run build

### Expected behavior

Build ends correctly

### Actual behavior

Build show error for every usage of $route and $router in TypeScript

**Comment by matteoscaramuzza** [comment]
Here's an example:

```
src/views/Customers/CustomerForm.vue:543:12 - error TS2339: Property '$router' does not exist on type 'CustomerForm'.

543       this.$router.replace({
```

**Comment by daniluk4000** [comment]
Same for our project, but can't reproduce in plain empty project. Weird...

**Comment by callumacrae** [comment]
Same issue here - `this.$route` and `this.$router` have lost their types, and so has `this.$store` and some other stuff we've defined in our env.d.ts

I'll try to work on a reproduction as this issue hasn't provided one, but I'm super busy today so I dunno when I'll be able to provide it! If anyone else can provide one first that would be great :)
